export const PLANS = {
  plan_a_subscription: {
    id: "plan_a_subscription",
    name: "30-Day Teacher Unlock",
    description: "Unlock up to 5 shadow teacher contacts for 30 days. Renew anytime.",
    amountPaise: 49900,
    currency: "INR",
    durationDays: 30,
    stripePriceId: process.env["STRIPE_PLAN_A_PRICE_ID"] ?? null,
  },
  plan_b_per_contact: {
    id: "plan_b_per_contact",
    name: "Single Contact Unlock",
    description: "Unlock one professional's contact details permanently. Pay as you go.",
    amountPaise: 14900,
    currency: "INR",
    durationDays: null,
    stripePriceId: process.env["STRIPE_PLAN_B_PRICE_ID"] ?? null,
  },
  plan_c_featured: {
    id: "plan_c_featured",
    name: "Featured Listing (30 days)",
    description: "Boost your profile to the top of search results for 30 days. More visibility, more enquiries.",
    amountPaise: 29900,
    currency: "INR",
    durationDays: 30,
    stripePriceId: process.env["STRIPE_PLAN_C_PRICE_ID"] ?? null,
  },
  plan_d_pro_onetime: {
    id: "plan_d_pro_onetime",
    name: "Professional Listing Fee (One-time)",
    description: "One-time fee to activate your professional profile and get listed on Sproutly.",
    amountPaise: 99900,
    currency: "INR",
    durationDays: null,
    stripePriceId: process.env["STRIPE_PLAN_D_PRICE_ID"] ?? null,
  },
  plan_e_pro_monthly: {
    id: "plan_e_pro_monthly",
    name: "Professional Monthly Subscription",
    description: "Monthly subscription required for neurologists and therapy centres to maintain an active premium listing.",
    amountPaise: 49900,
    currency: "INR",
    durationDays: 30,
    stripePriceId: process.env["STRIPE_PLAN_E_PRICE_ID"] ?? null,
  },
  plan_f_per_booking: {
    id: "plan_f_per_booking",
    name: "Specialist Booking",
    description: "Book one session with a specialist (OT, Speech, Special Tutor, Medical Specialist, or Therapy Centre). No subscription needed.",
    amountPaise: 4900,
    currency: "INR",
    durationDays: null,
    stripePriceId: process.env["STRIPE_PLAN_F_PRICE_ID"] ?? null,
  },
  plan_session_pass_5: {
    id: "plan_session_pass_5",
    name: "5-Session Pass",
    description: "Purchase 5 session credits for ₹245. Each credit covers one confirmed session slot.",
    amountPaise: 24500,
    currency: "INR",
    durationDays: null,
    stripePriceId: null,
  },
  plan_session_pass_10: {
    id: "plan_session_pass_10",
    name: "10-Session Pass",
    description: "Purchase 10 session credits for ₹490. Save more with the larger pack.",
    amountPaise: 49000,
    currency: "INR",
    durationDays: null,
    stripePriceId: null,
  },
} as const;

export type PlanId = keyof typeof PLANS;
