import { Router, type IRouter } from "express";
import healthRouter from "./health";
import usersRouter from "./users";
import professionalsRouter from "./professionals";
import ratingsRouter from "./ratings";
import unlocksRouter from "./unlocks";
import dashboardRouter from "./dashboard";
import complianceRouter from "./compliance";
import paymentsRouter from "./payments";
import adminRouter from "./admin";
import notificationsRouter from "./notifications";
import storageRouter from "./storage";
import verificationsRouter from "./verifications";
import accountRouter from "./account";
import sessionsRouter from "./sessions";
import childrenRouter from "./children";
import connectRouter from "./connect";
import engagementsRouter from "./engagements";
import walletRouter from "./wallet";
import assessmentsRouter from "./assessments";
import communityRouter from "./community";
import resourcesRouter from "./resources";
import referralsRouter from "./referrals";
import shadowTeacherRouter from "./shadowTeacher";
import { sessionsV2Router } from "./sessionsV2";
import lifecycleRouter from "./lifecycleRequests";
import dailyLogsRouter from "./dailyLogs";
import salaryPaymentsRouter from "./salaryPayments";
import parentNeedsRouter from "./parentNeeds";
import centresRouter from "./centres";

const router: IRouter = Router();

router.use(healthRouter);
router.use(usersRouter);
router.use(professionalsRouter);
router.use(ratingsRouter);
router.use(unlocksRouter);
router.use(dashboardRouter);
router.use(complianceRouter);
router.use(paymentsRouter);
router.use(adminRouter);
router.use(notificationsRouter);
router.use(storageRouter);
router.use(verificationsRouter);
router.use(accountRouter);
router.use(sessionsRouter);
router.use(childrenRouter);
router.use(connectRouter);
router.use(engagementsRouter);
router.use(walletRouter);
router.use(assessmentsRouter);
router.use(communityRouter);
router.use(resourcesRouter);
router.use(referralsRouter);
router.use(shadowTeacherRouter);
router.use(sessionsV2Router);
router.use(lifecycleRouter);
router.use(dailyLogsRouter);
router.use(salaryPaymentsRouter);
router.use(parentNeedsRouter);
router.use(centresRouter);

export default router;
