import { Router, type IRouter } from "express";
import healthRouter from "./health";
import usersRouter from "./users";
import professionalsRouter from "./professionals";
import ratingsRouter from "./ratings";
import unlocksRouter from "./unlocks";
import dashboardRouter from "./dashboard";
import complianceRouter from "./compliance";
import paymentsRouter from "./payments";
import adminRouter from "./admin";
import notificationsRouter from "./notifications";
import storageRouter from "./storage";
import verificationsRouter from "./verifications";
import accountRouter from "./account";
import sessionsRouter from "./sessions";
import childrenRouter from "./children";
import connectRouter from "./connect";
import engagementsRouter from "./engagements";
import walletRouter from "./wallet";

const router: IRouter = Router();

router.use(healthRouter);
router.use(usersRouter);
router.use(professionalsRouter);
router.use(ratingsRouter);
router.use(unlocksRouter);
router.use(dashboardRouter);
router.use(complianceRouter);
router.use(paymentsRouter);
router.use(adminRouter);
router.use(notificationsRouter);
router.use(storageRouter);
router.use(verificationsRouter);
router.use(accountRouter);
router.use(sessionsRouter);
router.use(childrenRouter);
router.use(connectRouter);
router.use(engagementsRouter);
router.use(walletRouter);

export default router;
