// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/onboard-stage1/RolePicker.tsx": () => import("../components/mockups/onboard-stage1/RolePicker.tsx")
};
